name: my_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy
  - sqlalchemy
  - psycopg2
  - click
  - pyarrow
  - python-dotenv
  - matplotlib
  - seaborn
  - jupyter
  - scikit-learn
  - pip
  - pip:
    - pre-commit